import Foundation

enum DemoData {
    private static let allOperationalComponents = [
        StatusComponent(id: "1", name: "API", status: .operational),
        StatusComponent(id: "2", name: "Claude.ai Web", status: .operational),
        StatusComponent(id: "3", name: "claude.ai on iOS", status: .operational),
        StatusComponent(id: "4", name: "API Cloudflare Worker", status: .operational),
    ]

    static func scenario(_ number: Int) -> (UsageResponse, StatusSummary, [String: [UtilizationSample]]) {
        switch number {
        case 1: return scenario1()
        case 2: return scenario2()
        case 3: return scenario3()
        case 4: return scenario4()
        default: return scenario1()
        }
    }

    private static func makeSamples(_ offsets: [(TimeInterval, Int)], resetsAt: Date) -> [UtilizationSample] {
        offsets.map { UtilizationSample(utilization: $0.1, timestamp: resetsAt.addingTimeInterval($0.0)) }
    }

    // MARK: - Demo Samples (generated by scripts/generate-demo-samples.py)

    // Scenario 1: Slow consumption (5h window, 42%)
    private static let samples_s1_5h: [(TimeInterval, Int)] = [
        (-18000, 0), (-17655, 0), (-17310, 2), (-16965, 4), (-16620, 7), (-16275, 9),
        (-15930, 12), (-15585, 12), (-15240, 13), (-14895, 13), (-14550, 16), (-14205, 19),
        (-13860, 19), (-13515, 21), (-13170, 25), (-12825, 26), (-12480, 26), (-12135, 30),
        (-11790, 32), (-11445, 32), (-11100, 36), (-10755, 37), (-10410, 37), (-10065, 38),
        (-9720, 42)
    ]

    // Scenario 1: Slow 7d window (18%)
    private static let samples_s1_7d: [(TimeInterval, Int)] = [
        (-604800, 1), (-593432, 1), (-582064, 1), (-570695, 1), (-559327, 5), (-547958, 5),
        (-536590, 6), (-525222, 7), (-513853, 7), (-502485, 10), (-491116, 10), (-479748, 10),
        (-468379, 12), (-457011, 12), (-445643, 14), (-434274, 14), (-422906, 15), (-411537, 15),
        (-400169, 15), (-388800, 18)
    ]

    // Scenario 2: Fast consumption with gap (5h window, 74%)
    private static let samples_s2_5h: [(TimeInterval, Int)] = [
        (-18000, 0), (-17615, 0), (-17229, 4), (-16843, 6), (-16458, 9), (-16072, 13),
        (-15686, 14), (-15300, 17), (-14915, 19), (-14529, 22), (-14143, 27), (-13758, 28),
        (-13372, 31), (-12986, 31), (-12600, 36), (-10200, 36), (-9832, 40), (-9463, 45),
        (-9095, 46), (-8726, 48), (-8358, 51), (-7989, 54), (-7620, 57), (-7252, 57),
        (-6883, 59), (-6515, 63), (-6146, 65), (-5778, 67), (-5409, 73), (-5040, 74)
    ]

    // Scenario 2: Moderate 7d window (61%)
    private static let samples_s2_7d: [(TimeInterval, Int)] = [
        (-604800, 1), (-594720, 1), (-584640, 5), (-574560, 7), (-564480, 11), (-554400, 12),
        (-544320, 14), (-534240, 16), (-524160, 20), (-514080, 21), (-504000, 25), (-493920, 29),
        (-483840, 30), (-473760, 31), (-463680, 37), (-453600, 38), (-443520, 39), (-433440, 41),
        (-423360, 44), (-413280, 48), (-403200, 52), (-393120, 53), (-383040, 54), (-372960, 57),
        (-362880, 61)
    ]

    // Scenario 3: Very high consumption (5h window, 91%)
    private static let samples_s3_5h: [(TimeInterval, Int)] = [
        (-18000, 0), (-17370, 2), (-16740, 9), (-16110, 12), (-15480, 13), (-14850, 17),
        (-14220, 23), (-13590, 25), (-12960, 28), (-12330, 35), (-11700, 38), (-11070, 41),
        (-10440, 46), (-9810, 50), (-9180, 51), (-8550, 55), (-7920, 60), (-7290, 64),
        (-6660, 68), (-6030, 72), (-5400, 76), (-4770, 81), (-4140, 81), (-3510, 86),
        (-2880, 91)
    ]

    // Scenario 3: High 7d window (85%)
    private static let samples_s3_7d: [(TimeInterval, Int)] = [
        (-604800, 0), (-585000, 4), (-565200, 6), (-545400, 9), (-525600, 13), (-505800, 17),
        (-486000, 20), (-466200, 23), (-446400, 30), (-426600, 31), (-406800, 36), (-387000, 39),
        (-367200, 40), (-347400, 48), (-327600, 50), (-307800, 55), (-288000, 58), (-268200, 61),
        (-248400, 62), (-228600, 67), (-208800, 69), (-189000, 73), (-169200, 76), (-149400, 80),
        (-129600, 85)
    ]

    // Scenario 4: Exhausted — hit 100% ~30min ago (5h window, 100%)
    private static let samples_s4_5h: [(TimeInterval, Int)] = [
        (-18000, 1), (-17632, 4), (-17264, 10), (-16896, 15), (-16528, 16), (-16160, 23),
        (-15791, 27), (-15423, 31), (-15055, 35), (-14687, 41), (-14319, 43), (-13950, 49),
        (-13582, 54), (-13214, 60), (-12846, 65), (-12478, 67), (-12110, 72), (-11741, 75),
        (-11373, 83), (-11005, 87), (-10637, 90), (-10269, 96), (-9900, 100), (-9600, 100),
        (-9300, 100), (-9000, 100), (-8700, 100), (-8400, 100), (-8100, 100)
    ]

    // Scenario 4: Gentle 7d window (38%)
    private static let samples_s4_7d: [(TimeInterval, Int)] = [
        (-604800, 0), (-592200, 0), (-579600, 4), (-567000, 4), (-554400, 7), (-541800, 8),
        (-529200, 8), (-516600, 10), (-504000, 10), (-491400, 15), (-478800, 17), (-466200, 18),
        (-453600, 18), (-441000, 18), (-428400, 23), (-415800, 25), (-403200, 25), (-390600, 26),
        (-378000, 26), (-365400, 31), (-352800, 32), (-340200, 32), (-327600, 34), (-315000, 36),
        (-302400, 38)
    ]

    // Scenario 4: Very gentle 7d Sonnet window (22%)
    private static let samples_s4_7d_sonnet: [(TimeInterval, Int)] = [
        (-604800, 0), (-588885, 2), (-572969, 2), (-557053, 2), (-541137, 4), (-525222, 6),
        (-509306, 6), (-493390, 7), (-477474, 11), (-461558, 11), (-445643, 11), (-429727, 12),
        (-413811, 12), (-397895, 13), (-381979, 15), (-366064, 17), (-350148, 17), (-334232, 18),
        (-318316, 19), (-302400, 22)
    ]

    private static func scenario1() -> (UsageResponse, StatusSummary, [String: [UtilizationSample]]) {
        let resetsAt5h = Date().addingTimeInterval(2.7 * Constants.Time.secondsPerHour)
        let resetsAt7d = Date().addingTimeInterval(4.5 * Constants.Time.secondsPerDay)
        let usage = UsageResponse(entries: [
            .make(key: "five_hour", utilization: 42, resetsAt: resetsAt5h),
            .make(key: "seven_day", utilization: 18, resetsAt: resetsAt7d),
        ])
        let samples = [
            "five_hour": makeSamples(samples_s1_5h, resetsAt: resetsAt5h),
            "seven_day": makeSamples(samples_s1_7d, resetsAt: resetsAt7d),
        ]
        let status = StatusSummary(
            components: [
                StatusComponent(id: "1", name: "API", status: .majorOutage),
                StatusComponent(id: "2", name: "Claude.ai Web", status: .partialOutage),
                StatusComponent(id: "3", name: "claude.ai on iOS", status: .operational),
                StatusComponent(id: "4", name: "API Cloudflare Worker", status: .operational),
            ],
            incidents: [
                Incident(
                    id: "i1",
                    name: "API Errors and Degraded Performance",
                    status: "investigating",
                    impact: "critical",
                    shortlink: "https://stspg.io/demo1a"
                ),
                Incident(
                    id: "i2",
                    name: "Elevated Error Rates on claude.ai",
                    status: "identified",
                    impact: "major",
                    shortlink: "https://stspg.io/demo1b"
                ),
            ],
            status: PageStatus(indicator: "major", description: "Major Service Outage")
        )
        return (usage, status, samples)
    }

    private static func scenario2() -> (UsageResponse, StatusSummary, [String: [UtilizationSample]]) {
        let resetsAt5h = Date().addingTimeInterval(1.4 * Constants.Time.secondsPerHour)
        let resetsAt7d = Date().addingTimeInterval(4.2 * Constants.Time.secondsPerDay)
        let usage = UsageResponse(entries: [
            .make(key: "five_hour", utilization: 74, resetsAt: resetsAt5h),
            .make(key: "seven_day", utilization: 61, resetsAt: resetsAt7d),
        ])
        let samples = [
            "five_hour": makeSamples(samples_s2_5h, resetsAt: resetsAt5h),
            "seven_day": makeSamples(samples_s2_7d, resetsAt: resetsAt7d),
        ]
        let status = StatusSummary(
            components: [
                StatusComponent(id: "1", name: "API", status: .degradedPerformance),
                StatusComponent(id: "2", name: "Claude.ai Web", status: .operational),
                StatusComponent(id: "3", name: "claude.ai on iOS", status: .operational),
                StatusComponent(id: "4", name: "API Cloudflare Worker", status: .operational),
            ],
            incidents: [
                Incident(
                    id: "i3",
                    name: "Increased API Latency",
                    status: "monitoring",
                    impact: "minor",
                    shortlink: "https://stspg.io/demo2"
                ),
            ],
            status: PageStatus(indicator: "minor", description: "Minor Service Disruption")
        )
        return (usage, status, samples)
    }

    private static func scenario3() -> (UsageResponse, StatusSummary, [String: [UtilizationSample]]) {
        let resetsAt5h = Date().addingTimeInterval(0.8 * Constants.Time.secondsPerHour)
        let resetsAt7d = Date().addingTimeInterval(1.5 * Constants.Time.secondsPerDay)
        let usage = UsageResponse(entries: [
            .make(key: "five_hour", utilization: 91, resetsAt: resetsAt5h),
            .make(key: "seven_day", utilization: 85, resetsAt: resetsAt7d),
            .make(key: "seven_day_sonnet", utilization: 0, resetsAt: nil),
        ])
        let samples = [
            "five_hour": makeSamples(samples_s3_5h, resetsAt: resetsAt5h),
            "seven_day": makeSamples(samples_s3_7d, resetsAt: resetsAt7d),
        ]
        let status = StatusSummary(
            components: allOperationalComponents,
            incidents: [],
            status: PageStatus(indicator: "none", description: "All Systems Operational")
        )
        return (usage, status, samples)
    }

    private static func scenario4() -> (UsageResponse, StatusSummary, [String: [UtilizationSample]]) {
        let resetsAt5h = Date().addingTimeInterval(2.25 * Constants.Time.secondsPerHour)
        let resetsAt7d = Date().addingTimeInterval(3.5 * Constants.Time.secondsPerDay)
        let usage = UsageResponse(entries: [
            .make(key: "five_hour", utilization: 100, resetsAt: resetsAt5h),
            .make(key: "seven_day", utilization: 38, resetsAt: resetsAt7d),
            .make(key: "seven_day_sonnet", utilization: 22, resetsAt: resetsAt7d),
        ])
        let samples = [
            "five_hour": makeSamples(samples_s4_5h, resetsAt: resetsAt5h),
            "seven_day": makeSamples(samples_s4_7d, resetsAt: resetsAt7d),
            "seven_day_sonnet": makeSamples(samples_s4_7d_sonnet, resetsAt: resetsAt7d),
        ]
        let status = StatusSummary(
            components: allOperationalComponents,
            incidents: [],
            status: PageStatus(indicator: "none", description: "All Systems Operational")
        )
        return (usage, status, samples)
    }
}
